#ifndef ORBIT_LWIPOPTS_H
#define ORBIT_LWIPOPTS_H
#define NO_SYS 1
#define LWIP_SOCKET 0
#define LWIP_NETCONN 0
#define LWIP_DHCP 1
#define LWIP_DNS 1
#define LWIP_TCP 1
#define LWIP_UDP 1
#define LWIP_ICMP 1
#define LWIP_ARP 1
#define LWIP_ETHERNET 1
#define LWIP_NETIF_STATUS_CALLBACK 1
#define LWIP_NETIF_LINK_CALLBACK 1
#define LWIP_NETIF_HOSTNAME 1
#define LWIP_ALTCP 1
#define LWIP_ALTCP_TLS 1
#define LWIP_ALTCP_TLS_MBEDTLS 1
#define MEM_LIBC_MALLOC 1
#define MEMP_MEM_MALLOC 1
#define MEM_ALIGNMENT 4
#define MEM_SIZE 4000
#define TCP_MSS 1460
#define TCP_WND (8*TCP_MSS)
#define TCP_SND_BUF (4*TCP_MSS)
#define TCP_SND_QUEUELEN 16
#define PBUF_POOL_SIZE 16
#define LWIP_TCP_KEEPALIVE 1
#define LWIP_STATS 0
#endif
