//! Opt-in release mutation target. Inputs are generated by scripts/fuzzing/check_parsers.py.
use crate::grants::{Expected, Keys, verify};
use base64::{Engine, engine::general_purpose::URL_SAFE_NO_PAD};
use jsonwebtoken::{Algorithm, EncodingKey};
use std::io::{BufReader, Read};

#[test]
#[ignore = "requires a bounded ORBIT_PARSER_FUZZ_INPUT corpus"]
fn bounded_parser_fuzz() {
    let corpus_path = std::env::var_os("ORBIT_SDK_GRANT_VECTORS")
        .map(std::path::PathBuf::from)
        .unwrap_or_else(|| {
            std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
                .join("../../contracts/sdk/grants.json")
        });
    let corpus: serde_json::Value =
        serde_json::from_slice(&std::fs::read(corpus_path).unwrap()).unwrap();
    let token = corpus["cases"]
        .as_array()
        .unwrap()
        .iter()
        .find(|case| case["name"] == "strict-valid")
        .unwrap()["token"]
        .as_str()
        .unwrap();
    let parts: Vec<_> = token.split('.').collect();
    let keys = Keys::parse(corpus["jwks"].clone()).unwrap();
    let expected = Expected {
        issuer: "https://orbit.example.test",
        application: "app",
        environment: "test",
        licence: Some("licence"),
        activation: "activation",
        installation: "installation",
        fingerprint: None,
        fingerprint_provider: None,
        credential_expires_at: 1_800_090_000,
        licence_expires_at: None,
        now: 1_800_000_000,
    };
    jsonwebtoken::crypto::aws_lc::DEFAULT_PROVIDER
        .install_default()
        .ok();
    let signing =
        EncodingKey::from_ec_pem(include_bytes!("../tests/fixtures/es256-test-private.pem"))
            .unwrap();
    let sign = |header: &str, payload: &str| {
        let message = format!("{header}.{payload}");
        let signature =
            jsonwebtoken::crypto::sign(message.as_bytes(), &signing, Algorithm::ES256).unwrap();
        format!("{message}.{signature}")
    };
    assert!(verify(token, &keys, &expected).is_ok());
    let input = std::env::var_os("ORBIT_PARSER_FUZZ_INPUT").expect("explicit corpus required");
    let mut reader = BufReader::new(std::fs::File::open(input).unwrap());
    let mut counts = [0_u64; 5];
    let mut accepted = [0_u64; 5];
    let mut longest = std::time::Duration::ZERO;
    let mut index = 0;
    loop {
        let mut mode = [0_u8];
        if reader.read(&mut mode).unwrap() == 0 {
            break;
        }
        let mut frame = [0_u8; 5];
        reader.read_exact(&mut frame).unwrap();
        let length = u32::from_le_bytes(frame[1..].try_into().unwrap()) as usize;
        assert!(length <= 1024 * 1024 + 1);
        let mut bytes = vec![0; length];
        reader.read_exact(&mut bytes).unwrap();
        let target = usize::from(mode[0]);
        assert!(target < counts.len() && frame[0] <= 2);
        let started = std::time::Instant::now();
        let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
            let success = match target {
                0..=2 => {
                    let token = match target {
                        0 => String::from_utf8(bytes.clone()).ok(),
                        1 => Some(sign(parts[0], &URL_SAFE_NO_PAD.encode(&bytes))),
                        _ => Some(sign(&URL_SAFE_NO_PAD.encode(&bytes), parts[1])),
                    };
                    let result = token
                        .as_deref()
                        .and_then(|value| verify(value, &keys, &expected).ok());
                    if let Some(claims) = &result {
                        // Authority may never cross the caller's expected scope, binding or time.
                        assert_eq!(claims.sub, "licence");
                        assert_eq!(claims.application_id, "app");
                        assert_eq!(claims.environment_id, "test");
                        assert_eq!(claims.activation_id, "activation");
                        assert_eq!(claims.installation_id, "installation");
                        assert_eq!(claims.binding_mode, "none");
                        assert!(
                            claims.fingerprint.is_none() && claims.fingerprint_provider.is_none()
                        );
                        assert!(
                            claims.exp > expected.now
                                && claims.exp <= expected.credential_expires_at
                        );
                        assert!(token.as_ref().unwrap().len() <= 16_384);
                    }
                    result.is_some()
                }
                3 => serde_json::from_slice(&bytes)
                    .ok()
                    .and_then(|value| Keys::parse(value).ok())
                    .is_some(),
                4 => {
                    let result = std::str::from_utf8(&bytes).ok().and_then(|identity| {
                        crate::machine_fingerprint("app", "test", "linux", identity).ok()
                    });
                    if let Some(fingerprint) = &result {
                        assert_eq!(fingerprint.len(), 64);
                        assert!(fingerprint.bytes().all(|byte| byte.is_ascii_hexdigit()));
                        let identity = std::str::from_utf8(&bytes).unwrap();
                        assert_ne!(
                            fingerprint,
                            &crate::machine_fingerprint("other", "test", "linux", identity)
                                .unwrap()
                        );
                        assert!(
                            crate::machine_fingerprint("app\ninjected", "test", "linux", identity)
                                .is_err()
                        );
                    }
                    result.is_some()
                }
                _ => unreachable!(),
            };
            if frame[0] != 2 {
                assert_eq!(success, frame[0] == 1);
            }
            success
        }))
        .unwrap_or_else(|_| panic!("reproducer record {index}, target {target}"));
        let elapsed = started.elapsed();
        longest = longest.max(elapsed);
        assert!(
            elapsed.as_secs() < 2,
            "slow record {index}, target {target}"
        );
        counts[target] += 1;
        accepted[target] += u64::from(result);
        index += 1;
    }
    assert!(counts.iter().all(|count| *count > 0), "incomplete corpus");
    println!(
        "ORBIT_FUZZ_RESULT cases={counts:?} accepted={accepted:?} max_case_us={}",
        longest.as_micros()
    );
}
